const ROLES = {
  ADMIN: "ADMIN",
  EDITOR: "EDITOR",
  VIEWER: "VIEWER",
};

const PERMISSIONS = {
  CREATE_POST: "CREATE_POST",
  UPDATE_POST: "UPDATE_POST",
  DELETE_POST: "DELETE_POST",
  APPROVE_POST: "APPROVE_POST",
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
};

const ROLE_PERMISSIONS = {
  ADMIN: Object.values(PERMISSIONS),

  EDITOR: [
    PERMISSIONS.CREATE_POST,
    PERMISSIONS.UPDATE_POST,
    PERMISSIONS.VIEW_DASHBOARD,
  ],

  VIEWER: [
    PERMISSIONS.VIEW_DASHBOARD,
  ],
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
};